INSERT INTO skills (name)
VALUES ('Java'),
       ('Spring Boot'),
       ('PostgreSQL'),
       ('Kotlin'),
       ('Coroutines'),
       ('C++'),
       ('STL'),
       ('Multithreading'),
       ('Embedded C'),
       ('RTOS'),
       ('React'),
       ('TypeScript'),
       ('CSS3'),
       ('JavaScript'),
       ('Vue.js'),
       ('Python'),
       ('Django'),
       ('Docker'),
       ('Pandas'),
       ('Scikit-learn'),
       ('Golang'),
       ('gRPC'),
       ('Kubernetes'),
       ('AWS'),
       ('Swift'),
       ('SwiftUI'),
       ('Combine'),
       ('Android SDK'),
       ('Network Security'),
       ('SIEM'),
       ('CISM'),
       ('Penetration Testing'),
       ('SQL'),
       ('Tableau'),
       ('BPMN'),
       ('UML'),
       ('System Analysis'),
       ('Terraform'),
       ('Ansible'),
       ('Prometheus'),
       ('CI/CD'),
       ('Selenium'),
       ('JUnit'),
       ('PyTest'),
       ('API Testing'),
       ('Agile'),
       ('Scrum'),
       ('Product Roadmap'),
       ('Jira'),
       ('Figma'),
       ('Adobe XD'),
       ('Prototyping');